package server

// Central dependency order for logical backup/restore. New durable modules must
// extend this list and the completeness test. Ephemeral credentials/presence are
// deliberately not restored. Never derive SQL identifiers from a backup archive.
var backupTables = []string{
	"users", "organizations", "organization_members", "workspaces", "workspace_members",
	"workspace_search_dictionary",
	"spaces", "space_members", "workspace_settings", "workspace_settings_history",
	"storage_providers", "storage_settings", "storage_assignments", "canvases", "canvas_shares",
	"documents", "document_shares", "document_versions", "document_access_requests", "favorites", "comments", "attachments",
	"knowledge_document_meta", "knowledge_document_history",
	"databases", "database_rows", "database_views", "database_view_preferences", "settings", "settings_history", "audit_logs", "notifications", "api_keys",
	"document_collaboration", "collaboration_updates", "collaboration_history_groups", "job_settings", "automation_webhooks", "automation_rules",
	"automation_events", "automation_jobs", "automation_job_attempts", "automation_effects",
	"backup_policy", "backup_artifacts",
	"plugins", "workspace_plugins", "plugin_storage",
	"teams", "team_members", "comment_reactions",
	"identity_links", "identity_grants", "identity_managed_members", "migration_imports",
	"migration_settings", "migration_sessions", "migration_session_items", "migration_session_chunks", "migration_session_objects", "migration_source_bindings",
	"scim_users", "scim_groups", "scim_group_members",
	"connector_settings", "connector_configs", "connector_records", "connector_runs",
	"capture_receipts", "attachment_receipts",
	"sql_sources", "sql_source_tables", "sql_source_queries", "sql_source_proposals", "sql_source_runs",
	"task_details",
	"calendar_events",
	"approval_policy_clock", "approval_policies", "approval_requests", "approval_assignments", "approval_decisions",
	"notification_settings", "notification_channels", "notification_preferences", "notification_deliveries",
	"inbound_capture_settings", "inbound_capture_channels", "inbound_capture_messages",
	"runbook_settings", "runbook_runners", "runbook_runner_versions", "runbook_documents", "runbook_executions", "runbook_execution_steps", "runbook_events",
	"protection_settings", "protection_settings_history", "protection_events",
	"public_shares", "public_share_visits",
	"document_relations",
	"rag_generations", "rag_generation_state", "rag_generation_validations", "rag_index_grants",
	"document_templates", "document_template_versions",
	"ai_conversations", "ai_messages",
	"knowledge_evidence_policy", "knowledge_evidence_policy_history", "knowledge_evidence", "knowledge_evidence_reviews",
	"knowledge_package_policy", "knowledge_package_policy_history", "knowledge_packages",
	"knowledge_change_events", "knowledge_impact_reviews", "knowledge_impact_review_events",
	"knowledge_impact_exceptions",
	"knowledge_proposals", "knowledge_proposal_events",
	"knowledge_conflict_runs", "knowledge_conflict_candidates", "knowledge_conflict_reviews", "knowledge_proposal_conflict_origins",
	"knowledge_validity", "knowledge_validity_periods", "knowledge_validity_history",
	"knowledge_questions", "knowledge_question_events", "knowledge_question_draft_receipts",
	"knowledge_structured_drafts",
	"document_split_receipts",
	"search_history_preferences", "search_history_entries",
	"workspace_agents", "agent_runs", "agent_events", "agent_sources", "agent_actions",
	"user_feature_flags", "user_feature_flags_history", "workspace_brand_assets",
	"git_sync_settings", "git_sync_connections", "git_sync_runs", "git_sync_mappings",
	"support_sessions",
	"export_settings", "export_runs",
	"knowledge_distribution_policy", "knowledge_distribution_policy_history", "knowledge_distribution_keys", "knowledge_distribution_imports", "knowledge_distribution_exports",
	"attachment_extraction_settings", "attachment_extraction_policy_history", "attachment_extractions",
	"system_status_policy", "system_status_policy_history", "system_status_cards", "system_status_reports",
	"user_worksets", "workset_items",
	"knowledge_paths", "knowledge_path_steps", "knowledge_path_progress", "knowledge_path_events",
	"graph_ai_runs", "graph_ai_sources", "graph_ai_actions", "graph_ai_annotations",
}

var ephemeralTables = []string{"sessions", "oidc_attempts", "handoff_claims", "collaboration_presence", "saml_authn_requests", "saml_assertion_replays", "notification_outbox", "search_chunks", "search_fragments", "search_folded_documents", "search_folded_fragments", "search_index_documents", "search_index_queue", "public_share_access", "public_share_rate_limits", "rag_vector_indexes", "rag_vector_chunks", "rag_reindex_queue", "operations_http_errors", "export_artifact_blobs", "knowledge_distribution_artifacts", "attachment_extraction_fragments", "attachment_extraction_heads"}
