CREATE TABLE IF NOT EXISTS workspace_agents (
 id uuid PRIMARY KEY, workspace_id uuid NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
 name text NOT NULL, instructions text NOT NULL DEFAULT '', enabled boolean NOT NULL DEFAULT false,
 revision bigint NOT NULL DEFAULT 1, space_ids uuid[] NOT NULL DEFAULT '{}', document_ids uuid[] NOT NULL DEFAULT '{}', database_ids uuid[] NOT NULL DEFAULT '{}',
 tools text[] NOT NULL DEFAULT '{}', max_steps integer NOT NULL DEFAULT 8 CHECK(max_steps BETWEEN 1 AND 24),
 max_tokens integer NOT NULL DEFAULT 4096 CHECK(max_tokens BETWEEN 1 AND 262144),
 created_by uuid NOT NULL REFERENCES users(id), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS agent_runs (
 id uuid PRIMARY KEY, agent_id uuid NOT NULL REFERENCES workspace_agents(id) ON DELETE CASCADE,
 workspace_id uuid NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, owner_id uuid NOT NULL REFERENCES users(id),
 token_id uuid REFERENCES api_keys(id) ON DELETE SET NULL, token_bound boolean NOT NULL DEFAULT false, actor_constraints jsonb NOT NULL DEFAULT '{}',
 agent_revision bigint NOT NULL, provider_fingerprint text NOT NULL, prompt text NOT NULL, session_hash text NOT NULL DEFAULT '',
 status text NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','running','awaiting_confirmation','succeeded','failed','cancelled')),
 step integer NOT NULL DEFAULT 0, messages jsonb NOT NULL DEFAULT '[]',
 output_bytes integer NOT NULL DEFAULT 0, job_id uuid, error text NOT NULL DEFAULT '',
 created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS agent_runs_owner ON agent_runs(owner_id,created_at DESC);
CREATE TABLE IF NOT EXISTS agent_events (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, run_id uuid NOT NULL REFERENCES agent_runs(id) ON DELETE CASCADE,
 event text NOT NULL, data jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS agent_events_run ON agent_events(run_id,id);
CREATE TABLE IF NOT EXISTS agent_sources (
 run_id uuid NOT NULL REFERENCES agent_runs(id) ON DELETE CASCADE, source_key text NOT NULL,
 kind text NOT NULL CHECK(kind IN ('document','database')), resource_id uuid NOT NULL,
 snapshot jsonb NOT NULL, fingerprint text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(),
 PRIMARY KEY(run_id,source_key)
);
CREATE TABLE IF NOT EXISTS agent_actions (
 id uuid PRIMARY KEY, run_id uuid NOT NULL REFERENCES agent_runs(id) ON DELETE CASCADE,
 tool_call_id text NOT NULL, tool text NOT NULL, arguments jsonb NOT NULL, action_hash text NOT NULL,
 status text NOT NULL DEFAULT 'planned' CHECK(status IN ('planned','confirmed','rejected','applied','cancelled','failed')),
 job_id uuid, result jsonb, confirmed_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(),
 UNIQUE(run_id,tool_call_id)
);
