import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {mkdir} from 'node:fs/promises';
import path from 'node:path';
import {zipSync,strToU8} from '../web/node_modules/fflate/esm/browser.js';
const base=process.env.MADI_BASE_URL||'http://127.0.0.1:8080',output=path.resolve(process.env.MADI_SCREENSHOT_DIR||'test-results/attachment-extraction');
await mkdir(output,{recursive:true});
const browser=await chromium.launch({headless:true});const context=await browser.newContext({viewport:{width:1440,height:1024},locale:'ko-KR'});const page=await context.newPage();const errors=[],external=[];
page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=500)errors.push(`${r.status()} ${r.url()}`);});page.on('request',r=>{if(!r.url().startsWith(base)&&!r.url().startsWith('data:')&&!r.url().startsWith('blob:'))external.push(r.url());});
async function api(p,method='GET',data){const r=await context.request.fetch(base+'/api/v1'+p,{method,data,headers:{'X-Madi-Request':'1'}});assert.ok(r.ok(),`${p}: ${r.status()} ${await r.text()}`);return r.json();}
async function upload(doc,name,buffer,mimeType){const r=await context.request.post(base+'/api/v1/attachments?document_id='+doc,{headers:{'X-Madi-Request':'1'},multipart:{file:{name,buffer,mimeType}}});assert.ok(r.ok(),await r.text());return r.json();}
async function shot(name){await page.evaluate(()=>document.fonts.ready);await page.screenshot({path:path.join(output,name+'.png'),fullPage:!(await page.getByRole('dialog').isVisible().catch(()=>false))});}
async function ready(id){for(let i=0;i<100;i++){const v=await api('/attachments/'+id+'/extraction-context');if(v.runs[0]?.status==='ready')return v.runs[0];if(v.runs[0]?.status==='failed')throw new Error(v.runs[0].error);await new Promise(r=>setTimeout(r,250));}throw new Error('extraction did not complete');}
try{
 await page.goto(base+'/login');await api('/auth/login','POST',{email:process.env.MADI_TEST_EMAIL||'admin@example.test',password:process.env.MADI_TEST_PASSWORD||'Browser-Test-Password-2026!'});
 const workspace=await api('/workspaces','POST',{name:'첨부 근거 실제 검증 '+Date.now()});await page.evaluate(id=>localStorage.setItem('madi.workspace',id),workspace.id);
 await page.goto(base+'/admin/attachment-extraction');await page.getByRole('heading',{name:'첨부 본문 추출',exact:true}).waitFor();await page.getByLabel('첨부 본문 추출 사용').check();await page.getByLabel('선택 OCR 허용').check();await page.getByRole('button',{name:'정책 변경 검토',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'변경 적용',exact:true}).click();await page.getByRole('dialog').waitFor({state:'hidden'});await shot('admin-attachment-extraction');
 const doc=await api('/documents','POST',{workspace_id:workspace.id,title:'첨부 위치·검색 검증',markdown:'첨부 원본은 변경하지 않습니다.',visibility:'private'});
 const original='쿠버네티스 운영 근거입니다.\n두 번째 문단과 원본 위치를 확인합니다.\nAI에 자동 전송하지 않습니다.';
 const file=await upload(doc.id,'운영 근거.txt',Buffer.from(original),'text/plain');
 await page.goto(base+'/app/documents/'+doc.id);await page.getByRole('link',{name:'본문·위치 보기',exact:true}).click();await page.getByRole('heading',{name:'운영 근거.txt',exact:true}).waitFor();await page.getByRole('button',{name:'본문 추출 검토',exact:true}).click();await shot('attachment-extraction-review');await page.getByRole('button',{name:'본문 추출 요청',exact:true}).click();const run=await ready(file.id);await page.reload();await page.locator('.extract-fragment').first().waitFor();await page.locator('.extract-fragment').first().click();await page.getByText('근거 #1',{exact:false}).waitFor();await shot('attachment-text-position');
 await page.reload();assert.match(page.url(),/fragment=/);await page.locator('.extract-fragment.selected').waitFor();
 await page.goto(base+'/app/search?type=file&q='+encodeURIComponent('쿠버네티스'));await page.getByText('운영 근거.txt',{exact:true}).first().waitFor();await shot('attachment-body-search');
 const word=Buffer.from(zipSync({'[Content_Types].xml':strToU8('<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/></Types>'),'_rels/.rels':strToU8('<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="r1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>'),'word/document.xml':strToU8('<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body><w:p><w:r><w:t>Office 운영 가이드</w:t></w:r></w:p><w:tbl><w:tr><w:tc><w:p><w:r><w:t>원본 표의 셀 근거</w:t></w:r></w:p></w:tc></w:tr></w:tbl></w:body></w:document>')}));
 const office=await upload(doc.id,'운영 가이드.docx',word,'application/vnd.openxmlformats-officedocument.wordprocessingml.document');await page.goto(base+'/app/attachments/'+office.id);await page.getByRole('button',{name:'본문 추출 검토',exact:true}).click();await page.getByRole('button',{name:'본문 추출 요청',exact:true}).click();await ready(office.id);await page.reload();await page.getByRole('button',{name:/표 1.*원본 표의 셀 근거/}).click();await shot('attachment-office-position');
 if(process.env.MADI_TEST_AI_URL){await api('/admin/settings','PUT',{ai_enabled:true,ai_base_url:process.env.MADI_TEST_AI_URL,ai_model:'local-attachment-test',ai_max_tokens:262144});await page.goto(base+'/app/attachments/'+file.id+'?extraction='+run.id);await page.locator('.extract-fragment').first().click();await page.getByRole('button',{name:'이 근거로 AI 질문',exact:true}).click();await page.getByRole('button',{name:'선택 본문 전송·답변 요청',exact:true}).waitFor();await shot('attachment-ai-consent');await page.getByRole('button',{name:'선택 본문 전송·답변 요청',exact:true}).click();await page.getByRole('heading',{name:'첨부 근거 기반 답변',exact:true}).waitFor();await page.getByRole('button',{name:'[1] 원본 위치·해시 확인',exact:true}).click();await page.getByRole('dialog').getByText(original.split('\n')[0],{exact:true}).waitFor();await shot('attachment-ai-citation');await page.getByRole('dialog').getByRole('button',{name:'닫기',exact:true}).click();}
 const pdfPage=await context.newPage();await pdfPage.setContent('<h1>Original PDF location</h1><p>Offline PDF.js rendering verification.</p>');const pdf=await pdfPage.pdf({format:'A4'});await pdfPage.close();const pdfFile=await upload(doc.id,'원본 위치.pdf',pdf,'application/pdf');await page.goto(base+'/app/attachments/'+pdfFile.id);await page.locator('.extract-canvas canvas').waitFor();await page.waitForFunction(()=>{const c=document.querySelector('.extract-canvas canvas');return c&&c.width>0&&c.height>0;});await page.waitForTimeout(1000);await shot('attachment-pdf-original');assert.equal(await page.getByText('PDF 원본을 표시하지 못했습니다.',{exact:false}).count(),0);
 await page.setViewportSize({width:390,height:844});await page.goto(base+'/app/attachments/'+file.id+'?extraction='+run.id);await page.locator('.extract-fragment').first().click();await page.getByRole('button',{name:'이 근거로 AI 질문',exact:true}).waitFor();await shot('attachment-position-mobile');assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1),'mobile overflow');
 assert.deepEqual(errors,[]);assert.deepEqual(external,[]);console.log('PASS actual text/Office jobs, source-position refresh/search, explicit AI stream/citation, local PDF.js original, mobile, JS0/external0');
}catch(e){await page.screenshot({path:path.join(output,'failure.png')}).catch(()=>{});throw e;}finally{await browser.close();}
