import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {mkdir} from 'node:fs/promises';
import path from 'node:path';
import http from 'node:http';
const base=process.env.MADI_BASE_URL||'http://127.0.0.1:8080';
const output=path.resolve(process.env.MADI_SCREENSHOT_DIR||'test-results/connectors');await mkdir(output,{recursive:true});
const upstream=http.createServer((req,res)=>{assert.equal(req.method,'GET');res.setHeader('Content-Type','application/json');res.end(JSON.stringify({items:[{id:'runbook-1',title:'원격 운영 Runbook',content:'# 운영 점검\n\n이 문서는 실제 사내 REST API에서 가져왔습니다.'}]}))});await new Promise(resolve=>upstream.listen(0,'127.0.0.1',resolve));const endpoint='http://127.0.0.1:'+upstream.address().port;
const browser=await chromium.launch({headless:true});const context=await browser.newContext({viewport:{width:1440,height:1000},locale:'ko-KR'});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=500)errors.push(`${r.status()} ${r.url()}`)});
async function api(endpoint,method='GET',data){const response=await context.request.fetch(base+'/api/v1'+endpoint,{method,data,headers:{'X-Madi-Request':'1'}});assert.ok(response.ok(),`${method} ${endpoint}: ${response.status()} ${await response.text()}`);return response.json()}
async function shot(name){await page.evaluate(()=>document.fonts.ready);await page.screenshot({path:path.join(output,name+'.png'),fullPage:!(await page.getByRole('dialog').count()),animations:'disabled',style:'.toast{visibility:hidden!important}'})}
let originalConnectorPolicy;
try{
 await page.goto(base+'/login');await api('/auth/login','POST',{email:process.env.MADI_TEST_EMAIL||'admin@example.test',password:process.env.MADI_TEST_PASSWORD||'Browser-Test-Password-2026!'});
 const workspace=await api('/workspaces','POST',{name:'커넥터 UI 검증 '+Date.now()});await page.evaluate(id=>localStorage.setItem('madi.workspace',id),workspace.id);const email='connector-ui-'+Date.now()+'@example.test';const service=await api('/admin/users','POST',{email,name:'연동 전용 계정',role:'editor',kind:'service'});await api(`/workspaces/${workspace.id}/members`,'PUT',{email,role:'editor'});
 const policy=await api('/admin/connectors/settings');originalConnectorPolicy=policy;await api('/admin/connectors/settings','PUT',{enabled:true,allowed_hosts:[...new Set([...(policy.allowed_hosts||[]),'127.0.0.1'])]});
 await page.goto(base+'/app/connectors');await page.getByRole('button',{name:'연결 추가',exact:true}).click();await page.getByLabel('연결 유형',{exact:true}).selectOption('rest');await page.getByLabel('연결 이름',{exact:true}).fill('운영 문서 REST');await page.getByLabel('API 기본 URL',{exact:true}).fill(endpoint);await page.getByLabel('전용 서비스 계정',{exact:true}).selectOption(service.id);await page.getByLabel('항목 배열 JSON 경로',{exact:true}).fill('items');await page.getByLabel('원격 고유 ID 경로',{exact:true}).fill('id');await page.getByLabel('제목 경로',{exact:true}).fill('title');await page.getByLabel('Markdown 본문 경로',{exact:true}).fill('content');await page.getByLabel('원격 접근 토큰',{exact:true}).fill('browser-connector-token');await page.getByLabel('사내망 HTTP 허용',{exact:false}).check();await page.getByLabel('원격 프로젝트가 비공개여도',{exact:false}).check();await page.getByLabel('이 연결 활성화',{exact:true}).check();await shot('connector-editor');await page.getByRole('button',{name:'연결 저장',exact:true}).click();await page.getByRole('dialog').waitFor({state:'hidden'});
 await page.getByRole('button',{name:'미리보기',exact:true}).click();await page.getByRole('cell',{name:/^1개 미리보기/}).waitFor({timeout:45000});await shot('connector-preview');const detailURL=page.url();await page.reload();await page.getByRole('dialog').waitFor();await page.getByRole('cell',{name:/^1개 미리보기/}).waitFor();assert.equal(page.url(),detailURL);await page.getByRole('button',{name:'닫기',exact:true}).click();await page.getByRole('button',{name:'가져오기',exact:true}).click();await page.getByRole('link',{name:'원격 운영 Runbook',exact:true}).waitFor({timeout:45000});await shot('connector-results');await page.getByRole('button',{name:'닫기',exact:true}).click();await shot('connectors');
 await page.getByRole('button',{name:'편집',exact:true}).click();assert.equal(await page.getByLabel('원격 접근 토큰',{exact:true}).inputValue(),'');await page.getByRole('button',{name:'취소',exact:true}).click();
 await page.goto(base+'/admin/connectors');await page.getByRole('heading',{name:'외부 연결 정책',exact:true}).waitFor();await shot('admin-connectors');await page.setViewportSize({width:390,height:844});await shot('admin-connectors-mobile');await page.goto(detailURL);await page.getByRole('dialog').waitFor();await page.getByRole('link',{name:'원격 운영 Runbook',exact:true}).waitFor();await shot('connector-results-mobile');assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'mobile overflow');assert.deepEqual(errors,[]);console.log(JSON.stringify({ok:true,workspace_id:workspace.id,screenshots:output}));
}finally{try{if(originalConnectorPolicy)await api('/admin/connectors/settings','PUT',{enabled:originalConnectorPolicy.enabled,allowed_hosts:originalConnectorPolicy.allowed_hosts||[]})}finally{await browser.close();await new Promise(resolve=>upstream.close(resolve))}}
