import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {mkdir} from 'node:fs/promises';
import path from 'node:path';
const base=process.env.MADI_BASE_URL||'http://127.0.0.1:8080',out=path.resolve(process.env.MADI_SCREENSHOT_DIR||'docs/screenshots');await mkdir(out,{recursive:true});
const browser=await chromium.launch({headless:true}),context=await browser.newContext({viewport:{width:1512,height:1080},locale:'ko-KR',timezoneId:'Asia/Seoul',reducedMotion:'reduce'}),page=await context.newPage(),issues=[];
page.on('pageerror',e=>issues.push(e.message));page.on('response',r=>{if(r.status()>=500)issues.push(`${r.status()} ${r.url()}`)});page.on('console',m=>{if(m.type()==='error'&&!m.text().includes('401 (Unauthorized)'))issues.push(m.text())});
await context.route('**/*',r=>new URL(r.request().url()).origin===new URL(base).origin?r.continue():r.abort());
async function api(endpoint,method='GET',data){const r=await context.request.fetch(`${base}/api/v1${endpoint}`,{method,data,headers:{'X-Madi-Request':'1'}});assert.ok(r.ok(),`${method} ${endpoint}: ${r.status()} ${await r.text()}`);return r.json()}
async function shot(name){await page.evaluate(()=>document.fonts.ready);if(await page.locator('.toast .icon-button').count())await page.locator('.toast .icon-button').click();await page.screenshot({path:path.join(out,`${name}.png`),fullPage:true,animations:'disabled'})}
try{
 const me=await api('/auth/login','POST',{email:process.env.MADI_TEST_EMAIL||'admin@example.test',password:process.env.MADI_TEST_PASSWORD||'Browser-Test-Password-2026!'});
 const ws=await api('/workspaces','POST',{name:'문서 토론 검증 워크스페이스'});await context.addInitScript(wid=>localStorage.setItem('madi.workspace',wid),ws.id);
 await page.goto(`${base}/app/teams`);await page.getByRole('heading',{name:'팀과 멘션 그룹',exact:true}).waitFor();await page.getByLabel('새 팀 이름',{exact:true}).fill('플랫폼 검토팀');await page.getByRole('button',{name:'팀 만들기',exact:true}).click();await page.getByRole('heading',{name:'플랫폼 검토팀',exact:true}).waitFor();const tid=new URL(page.url()).searchParams.get('team');assert.ok(tid);await page.getByLabel('추가할 워크스페이스 멤버',{exact:true}).selectOption(me.id);await page.getByRole('button',{name:'멤버 추가',exact:true}).click();await page.locator('.space-member-list').getByText(me.email,{exact:true}).waitFor();await page.reload();await page.getByRole('heading',{name:'플랫폼 검토팀',exact:true}).waitFor();await shot('teams');
 const doc=await api('/documents','POST',{workspace_id:ws.id,title:'함께 검토하는 운영 표준',markdown:'# 함께 검토하는 운영 표준\n\n매일 서비스 상태를 확인합니다.\n\n## 변경 검토\n\n변경 사항을 팀에 공유하고 근거를 기록합니다.\n',tags:['운영','협업']});
 await page.goto(`${base}/app/documents/${doc.id}?mode=read`);await page.getByRole('heading',{name:'댓글과 토론',exact:false}).waitFor();await page.getByLabel('댓글 내용',{exact:true}).fill('이번 운영 표준 변경을 검토해주세요.');await page.getByLabel('사용자·팀 언급',{exact:true}).selectOption(`team:${tid}`);await page.getByRole('button',{name:'인용·담당자',exact:true}).click();await page.getByLabel('인용 문장',{exact:true}).fill('매일 서비스 상태를 확인합니다.');await page.getByLabel('토론 담당자',{exact:true}).selectOption(me.id);await page.getByRole('button',{name:'댓글 등록',exact:true}).click();await page.locator('.discussion-comment').first().waitFor();let list=await api(`/documents/${doc.id}/comments`);assert.equal(list.length,1);const cid=list[0].id,thread=page.locator(`#comment-${cid}`);await thread.getByText('@플랫폼 검토팀',{exact:true}).waitFor();await thread.getByRole('button',{name:`${me.name} 댓글 thanks 반응`,exact:true}).click();await thread.getByRole('button',{name:'답글',exact:true}).click();await page.getByLabel('댓글 내용',{exact:true}).fill('확인했습니다. 점검 결과와 후속 조치도 연결하겠습니다.');await page.getByRole('button',{name:'댓글 등록',exact:true}).click();await page.locator('.discussion-comment').nth(1).waitFor();await thread.getByRole('button',{name:'해결',exact:true}).click();await thread.getByText('해결됨',{exact:true}).waitFor();await shot('document-discussion');
 await thread.getByRole('button',{name:'수정',exact:true}).click();const dialog=page.getByRole('dialog');await dialog.getByLabel('수정할 댓글',{exact:true}).fill('운영 표준 변경 검토를 완료했습니다.');await dialog.getByRole('button',{name:'수정 저장',exact:true}).click();await dialog.waitFor({state:'hidden'});await thread.getByText('운영 표준 변경 검토를 완료했습니다.',{exact:true}).waitFor();await page.reload();await thread.getByText('운영 표준 변경 검토를 완료했습니다.',{exact:true}).waitFor();await thread.getByText('해결됨',{exact:true}).waitFor();console.log('PASS teams, mentions, quote, assignment, reactions, threaded reply, resolve/edit and refresh');
 await page.goto(`${base}/app/documents/${doc.id}/knowledge`);await page.getByLabel('문서 상태',{exact:true}).selectOption('archived');await page.getByRole('button',{name:'운영 속성 저장',exact:true}).click();await page.getByText(/문서 v2 ·/).waitFor();await page.reload();await page.getByLabel('문서 상태',{exact:true}).waitFor();assert.equal(await page.getByLabel('문서 상태',{exact:true}).inputValue(),'archived');await shot('document-lifecycle');
 await page.goto(`${base}/app/workspace-settings`);await page.getByLabel('문서 생명주기 자동화',{exact:true}).selectOption('on');await page.getByRole('button',{name:'설정 저장',exact:true}).click();await page.getByText('설정 버전 2',{exact:true}).waitFor();await page.reload();await page.getByLabel('문서 생명주기 자동화',{exact:true}).waitFor();assert.equal(await page.getByLabel('문서 생명주기 자동화',{exact:true}).inputValue(),'on');console.log('PASS archive status and opt-in lifecycle settings persist');
 await page.setViewportSize({width:390,height:844});await page.goto(`${base}/app/teams?team=${tid}`);await page.getByRole('heading',{name:'플랫폼 검토팀',exact:true}).waitFor();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await shot('mobile-teams');await page.goto(`${base}/app/documents/${doc.id}?mode=read`);await page.locator('.discussion-comment').nth(1).waitFor();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await shot('mobile-document-discussion');assert.deepEqual(issues,[]);console.log('PASS desktop/mobile discussion zero overflow, zero external network and UI errors');
}finally{await browser.close()}
