import assert from 'node:assert/strict';
import {mkdir} from 'node:fs/promises';
import path from 'node:path';
import {chromium,expect} from 'playwright/test';
const base=process.env.MADI_BASE_URL,wid=process.env.MADI_WORKSPACE_ID,id=process.env.MADI_DOCUMENT_ID,source=process.env.MADI_SOURCE_ID,builder=process.env.MADI_BUILDER_ID;
const output=path.resolve(process.env.MADI_SCREENSHOT_DIR||'test-results/document-query');
const browser=await chromium.launch(),context=await browser.newContext({viewport:{width:1440,height:1000},locale:'ko-KR',reducedMotion:'reduce'}),admin=await browser.newContext(),page=await context.newPage();
const issues=[];let calls=0;page.on('pageerror',e=>issues.push(e.message));page.on('request',r=>{if(r.url().endsWith('/queries/execute'))calls++});page.on('response',r=>{if(r.url().startsWith(base+'/api/')&&r.status()>=500)issues.push(`HTTP${r.status()} ${r.url()}`)});
async function api(ctx,url,method='GET',data,status=200){const response=await ctx.request.fetch(base+'/api/v1'+url,{method,data,headers:{'X-Madi-Request':'1'}});assert.equal(response.status(),status,await response.text());return response.json()}
async function shot(name){await mkdir(output,{recursive:true});await page.screenshot({path:path.join(output,name+'.png'),fullPage:page.viewportSize().width>500&&await page.getByRole('dialog').count()===0,animations:'disabled'})}
try{
 await api(context,'/auth/login','POST',{email:'browser-query@example.test',password:'Query-Browser-Password-2026!'});await api(admin,'/auth/login','POST',{email:'admin@example.test',password:'Integration-Test-Password-2026!'});
 await page.goto(base+'/app');await page.getByLabel('워크스페이스 선택',{exact:true}).selectOption(wid);const before=await api(context,'/documents/'+id);await page.goto(base+`/app/documents/${id}?mode=read`);
 const block=page.getByRole('region',{name:'문서 선언형 조회',exact:true});await expect(block.getByRole('button',{name:'조회 실행',exact:true})).toBeEnabled();assert.equal(calls,0);await block.getByLabel('검색어 (필수)',{exact:true}).fill('운영');await shot('document-query-definition');await block.getByRole('button',{name:'조회 실행',exact:true}).click();
 await expect(block.getByRole('table')).toContainText('운영 점검 가이드');await expect(block.getByRole('table')).toContainText('2026-09-09');await expect(block.getByRole('table')).not.toContainText('PRIVATE_BROWSER_SENTINEL');assert.equal(calls,1);assert.equal(await block.locator('td').first().evaluate(el=>getComputedStyle(el).fontSize),'16px');const after=await api(context,'/documents/'+id);assert.equal(after.version,before.version);assert.equal(after.markdown,before.markdown);await shot('document-query-results');
 const sourceRow=block.getByRole('row').filter({hasText:'운영 점검 가이드'});await sourceRow.getByRole('button',{name:'원문 v1 보기',exact:true}).click();await expect(page.getByRole('dialog')).toContainText('담당자가 점검 결과');await page.getByRole('dialog').getByRole('button',{name:'닫기',exact:true}).click();await expect(sourceRow.getByRole('button',{name:'원문 v1 보기',exact:true})).toBeFocused();
 await page.emulateMedia({media:'print'});await expect(block.locator('.query-result')).toBeHidden();await page.emulateMedia({media:'screen'});
 await page.setViewportSize({width:390,height:844});await page.waitForFunction(()=>matchMedia('(max-width:640px)').matches&&getComputedStyle(document.querySelector('.main')).marginLeft==='0px',null,{timeout:2000});await block.scrollIntoViewIfNeeded();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await shot('document-query-mobile');
 await block.getByLabel('검색어 (필수)',{exact:true}).fill('없는조건');await expect(block.getByRole('table')).toHaveCount(0);await block.getByRole('button',{name:'조회 실행',exact:true}).click();await expect(block).toContainText('현재 범위와 조건에서 표시할 행이 없습니다');await block.getByLabel('검색어 (필수)',{exact:true}).fill('운영');await block.getByRole('button',{name:'조회 실행',exact:true}).click();await expect(block.getByRole('table')).toContainText('운영 점검 가이드');
 await api(admin,'/documents/'+source,'PUT',{version:1,visibility:'private'});await expect(block.getByRole('table')).toHaveCount(0,{timeout:8000});await expect(block).toContainText('조회 결과의 권한');await shot('document-query-revoked');
 await page.setViewportSize({width:1440,height:1000});await page.goto(base+`/app/documents/${builder}?mode=edit`);await page.getByRole('button',{name:'선언형 조회 표',exact:true}).click();const modal=page.getByRole('dialog',{name:'선언형 조회 표 넣기',exact:true});await modal.getByLabel('조회 대상',{exact:true}).selectOption('tasks');await expect(modal.getByLabel('할 일',{exact:true})).toBeChecked();await modal.getByLabel('조회 대상',{exact:true}).selectOption('relations');await modal.getByLabel('최대 경로 깊이',{exact:true}).selectOption('3');await modal.getByLabel('관계 방향',{exact:true}).selectOption('incoming');await modal.getByLabel('조회 대상',{exact:true}).selectOption('documents');await modal.getByLabel('추가 Front Matter 속성 (선택)',{exact:true}).fill('점검일');await modal.getByLabel('속성 유형',{exact:true}).selectOption('date');await modal.getByText('실행할 때 포함할 문구를 입력받기',{exact:true}).check();await shot('document-query-builder');await modal.getByRole('button',{name:'조회 정의 넣기',exact:true}).click();await expect(modal).toHaveCount(0);
 await expect.poll(async()=>{const doc=await api(context,'/documents/'+builder);return doc.markdown},{timeout:12000}).toContain('madi-query');const saved=await api(context,'/documents/'+builder);assert.ok(saved.markdown.includes('"점검일": "date"'));assert.ok(!saved.markdown.includes('운영 점검 가이드'));assert.deepEqual(issues,[]);console.log(JSON.stringify({ok:true,checks:['manual-execution','typed-parameters','private-filter','canonical-unchanged','source-preview-focus','print-excludes-results','mobile390','empty-recovery','ACL-invalidates-output','native-select-reset','definition-only-insertion'],screenshots:output}));
}catch(e){await shot('failure').catch(()=>{});console.error(await page.locator('body').innerText());throw e}finally{await browser.close()}
