import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {mkdir} from 'node:fs/promises';
import path from 'node:path';
const base=process.env.MADI_BASE_URL||'http://127.0.0.1:8080',out=path.resolve(process.env.MADI_SCREENSHOT_DIR||'docs/screenshots');await mkdir(out,{recursive:true});
const browser=await chromium.launch({headless:true}),context=await browser.newContext({viewport:{width:1512,height:1080},locale:'ko-KR',timezoneId:'Asia/Seoul',reducedMotion:'reduce'}),page=await context.newPage(),issues=[],external=[];
page.on('pageerror',e=>issues.push(e.message));page.on('response',r=>{if(r.status()>=500)issues.push(`${r.status()} ${r.url()}`)});page.on('console',m=>{if(m.type()==='error'&&!m.text().includes('401 (Unauthorized)'))issues.push(m.text())});
await context.route('**/*',r=>{if(new URL(r.request().url()).origin===new URL(base).origin)return r.continue();external.push(r.request().url());return r.abort()});
async function api(endpoint,method='GET',data){const r=await context.request.fetch(`${base}/api/v1${endpoint}`,{method,data,headers:{'X-Madi-Request':'1'}});assert.ok(r.ok(),`${method} ${endpoint}: ${r.status()} ${await r.text()}`);return r.json()}
async function shot(name){await page.evaluate(()=>document.fonts.ready);if(await page.locator('.toast .icon-button').count())await page.locator('.toast .icon-button').click();await page.screenshot({path:path.join(out,`${name}.png`),fullPage:true,animations:'disabled'})}
try{
 await api('/auth/login','POST',{email:process.env.MADI_TEST_EMAIL||'admin@example.test',password:process.env.MADI_TEST_PASSWORD||'Browser-Test-Password-2026!'});const ws=await api('/workspaces','POST',{name:'수집함 화면 검증'});await context.addInitScript(wid=>localStorage.setItem('madi.workspace',wid),ws.id);
 await page.goto(`${base}/app/inbox`);await page.getByRole('heading',{name:'내 수집함',exact:true}).waitFor();await page.getByLabel('수집 제목',{exact:true}).fill('GPU 운영 지식 아이디어');await page.getByLabel('수집할 내용',{exact:true}).fill('모델 운영 중 발견한 개선 사항을 먼저 기록합니다.\n\n- [ ] 팀에 공유할 참고자료 정리');await page.getByLabel('출처 URL',{exact:true}).fill('https://offline-reference.invalid/runbook');await page.getByLabel('수집 태그',{exact:true}).fill('아이디어, 운영');await page.getByLabel('수집 파일 첨부',{exact:true}).setInputFiles({name:'운영-참고자료.txt',mimeType:'text/plain',buffer:Buffer.from('폐쇄망 참고자료')});await page.getByRole('button',{name:'내 수집함에 저장',exact:true}).click();await page.locator('.capture-card').getByRole('link',{name:'GPU 운영 지식 아이디어',exact:true}).waitFor();await page.getByLabel('수집 제목',{exact:true}).waitFor();assert.equal(await page.getByLabel('수집 제목',{exact:true}).inputValue(),'');
 let records=await api(`/captures?workspace_id=${ws.id}`);assert.equal(records.length,1);const id=records[0].id;assert.equal(records[0].visibility,'private');const attachments=await api(`/documents/${id}/attachments`);assert.equal(attachments.length,1);await page.reload();await page.locator('.capture-card').getByRole('link',{name:'GPU 운영 지식 아이디어',exact:true}).waitFor();await shot('inbox');
 await page.getByRole('button',{name:'문서로 분류',exact:true}).click();const modal=page.getByRole('dialog');await modal.getByLabel('분류할 문서 종류',{exact:true}).selectOption('decision');await modal.getByLabel('대상 공간',{exact:true}).selectOption('');await modal.getByLabel('상위 문서',{exact:true}).selectOption('');await modal.getByLabel('분류 후 공유 범위',{exact:true}).selectOption('workspace');assert.equal(await modal.getByRole('button',{name:'분류 저장',exact:true}).isDisabled(),true);await modal.getByRole('checkbox').check();await shot('inbox-classify');await modal.getByRole('button',{name:'분류 저장',exact:true}).click();await modal.waitFor({state:'hidden'});await page.getByRole('heading',{name:'수집함이 비어 있습니다',exact:true}).waitFor();const doc=await api(`/documents/${id}`);assert.equal(doc.visibility,'workspace');assert.equal((await api(`/documents/${id}/knowledge`)).kind,'decision');assert.equal((await api(`/documents/${id}/attachments`)).length,1);
 console.log('PASS capture text/URL/tags/file, private-by-default, refresh, explicit publication confirmation, classify preserves source and attachments');
 await page.setViewportSize({width:390,height:844});await page.goto(`${base}/app/inbox?title=${encodeURIComponent('이동 중 떠오른 메모')}&text=${encodeURIComponent('모바일에서 빠르게 기록합니다.')}`);await page.getByLabel('수집 제목',{exact:true}).waitFor();assert.equal(await page.getByLabel('수집 제목',{exact:true}).inputValue(),'이동 중 떠오른 메모');await page.getByRole('button',{name:'내 수집함에 저장',exact:true}).click();await page.locator('.capture-card').getByRole('link',{name:'이동 중 떠오른 메모',exact:true}).waitFor();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await shot('mobile-inbox');await page.getByRole('button',{name:'문서로 분류',exact:true}).click();await modal.getByLabel('분류 후 공유 범위',{exact:true}).selectOption('private');assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await shot('mobile-inbox-classify');await modal.getByRole('button',{name:'분류 저장',exact:true}).click();await modal.waitFor({state:'hidden'});assert.deepEqual(issues,[]);assert.deepEqual(external,[]);console.log('PASS desktop/mobile inbox, zero overflow, external requests and browser errors');
}finally{await browser.close()}
