import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {mkdir} from 'node:fs/promises';
import path from 'node:path';
const base=process.env.MADI_BASE_URL||'http://127.0.0.1:8080',out=path.resolve(process.env.MADI_SCREENSHOT_DIR||'docs/screenshots');
await mkdir(out,{recursive:true});
const browser=await chromium.launch({headless:true}),context=await browser.newContext({viewport:{width:1512,height:1080},locale:'ko-KR',timezoneId:'Asia/Seoul',reducedMotion:'reduce'}),page=await context.newPage(),issues=[];
page.on('pageerror',e=>issues.push(e.message));page.on('response',r=>{if(r.status()>=500)issues.push(`${r.status()} ${r.url()}`)});page.on('console',m=>{if(m.type()==='error'&&!m.text().includes('401 (Unauthorized)'))issues.push(m.text())});
await context.route('**/*',r=>new URL(r.request().url()).origin===new URL(base).origin?r.continue():r.abort());
async function api(endpoint,method='GET',data){const r=await context.request.fetch(`${base}/api/v1${endpoint}`,{method,data,headers:{'X-Madi-Request':'1'}});assert.ok(r.ok(),`${method} ${endpoint}: ${r.status()} ${await r.text()}`);return r.json()}
async function shot(name){await page.evaluate(()=>document.fonts.ready);if(await page.locator('.toast .icon-button').count())await page.locator('.toast .icon-button').click();await page.screenshot({path:path.join(out,`${name}.png`),fullPage:true,animations:'disabled'})}
try{
 await api('/auth/login','POST',{email:process.env.MADI_TEST_EMAIL||'admin@example.test',password:process.env.MADI_TEST_PASSWORD||'Browser-Test-Password-2026!'});
 const ws=await api('/workspaces','POST',{name:'지식 운영 검증 워크스페이스'});await context.addInitScript(wid=>localStorage.setItem('madi.workspace',wid),ws.id);
 const doc=await api('/documents','POST',{workspace_id:ws.id,title:'서비스 운영 의사결정 기록',markdown:'# 배경\n\n지식의 소유권과 최신성을 관리합니다.\n\n## 결정\n\n[[플랫폼 운영 표준]]을 참고합니다. #운영\n',tags:['운영','정책']});
 await api('/documents','POST',{workspace_id:ws.id,title:'플랫폼 운영 표준',markdown:'# 플랫폼 운영 표준\n\n## 일상 점검\n\n'+('서비스 상태, 백업 결과와 지식의 소유권을 정기적으로 점검합니다. '.repeat(10))+'\n\n[[서비스 운영 의사결정 기록]] #운영',tags:['운영']});
 await page.goto(`${base}/app/documents/${doc.id}/knowledge`);await page.getByRole('heading',{name:doc.title,exact:true}).waitFor();await page.getByLabel('문서 종류',{exact:true}).selectOption('decision');await page.getByLabel('문서 등급',{exact:true}).selectOption('confidential');await page.getByLabel('문서 검토 주기 (일)',{exact:true}).fill('30');await page.getByLabel('검토 담당자',{exact:true}).selectOption({label:'관리자 · admin@example.test'});await page.getByRole('button',{name:'운영 속성 저장',exact:true}).click();await page.getByText(/문서 v2 ·/).waitFor();await page.reload();await page.getByLabel('문서 종류',{exact:true}).waitFor();assert.equal(await page.getByLabel('문서 종류',{exact:true}).inputValue(),'decision');assert.equal(await page.getByLabel('문서 등급',{exact:true}).inputValue(),'confidential');await shot('document-knowledge-policy');
 await page.getByRole('button',{name:'오늘 최신성 확인',exact:true}).click();await page.locator('.knowledge-policy details summary').filter({hasText:'최신성 확인'}).first().waitFor();await page.locator('.knowledge-policy details summary').filter({hasText:'정책 변경'}).first().click();await shot('document-knowledge-history');
 await page.getByLabel('법적 보존 — 해제하기 전까지 삭제 금지',{exact:true}).check();await page.getByRole('button',{name:'운영 속성 저장',exact:true}).click();await page.getByText(/문서 v3 ·/).waitFor();const held=await api(`/documents/${doc.id}/knowledge`);assert.equal(held.legal_hold,true);const denied=await context.request.delete(`${base}/api/v1/documents/${doc.id}`,{headers:{'X-Madi-Request':'1'}});assert.equal(denied.status(),409);console.log('PASS metadata native select, version, history, review and legal-hold deletion guard');
 await page.goto(`${base}/app/knowledge-health`);await page.getByRole('heading',{name:'지식 품질 관리',exact:true}).waitFor();await page.locator('.knowledge-documents').getByRole('link',{name:doc.title,exact:true}).waitFor();await shot('knowledge-health');await page.getByLabel('진단 항목',{exact:true}).selectOption('no_tags');await page.reload();await page.getByLabel('진단 항목',{exact:true}).waitFor();assert.equal(await page.getByLabel('진단 항목',{exact:true}).inputValue(),'no_tags');await page.getByLabel('진단 항목',{exact:true}).selectOption('');await page.getByRole('button',{name:`${doc.title} 품질 점수 상세`,exact:true}).click();await page.getByRole('dialog').waitFor();await shot('knowledge-quality-score');await page.getByRole('dialog').getByRole('button',{name:'닫기',exact:true}).click();
 await page.setViewportSize({width:390,height:844});await shot('mobile-knowledge-health');assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.goto(`${base}/app/documents/${doc.id}/knowledge`);await page.getByLabel('문서 종류',{exact:true}).waitFor();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await shot('mobile-document-knowledge');assert.deepEqual(issues,[]);console.log('PASS quality calculation, URL filter refresh, desktop/mobile captures and zero UI errors');
}finally{await browser.close()}
