import assert from 'node:assert/strict';
import {mkdir} from 'node:fs/promises';
import path from 'node:path';
import {chromium,expect} from 'playwright/test';
const base=process.env.MADI_BASE_URL,wid=process.env.MADI_WORKSPACE_ID,doc=process.env.MADI_DOCUMENT_ID,uid=process.env.MADI_ACTOR_ID;
const output=path.resolve(process.env.MADI_SCREENSHOT_DIR||'test-results/system-status');
const browser=await chromium.launch(),context=await browser.newContext({viewport:{width:1440,height:1000},locale:'ko-KR',reducedMotion:'reduce'}),page=await context.newPage();
const issues=[];page.on('pageerror',e=>issues.push(e.message));page.on('response',r=>{if(r.url().startsWith(base+'/api/')&&r.status()>=500)issues.push(`HTTP${r.status()} ${r.url()}`)});
async function api(url,method='GET',data,status=200){const response=await context.request.fetch(base+'/api/v1'+url,{method,data,headers:{'X-Madi-Request':'1'}});assert.equal(response.status(),status,await response.text());return response.json()}
async function shot(name){await mkdir(output,{recursive:true});await page.evaluate(()=>document.fonts.ready);await page.screenshot({path:path.join(output,name+'.png'),fullPage:page.viewportSize().width>500,animations:'disabled'})}
async function overflow(){const d=await page.evaluate(()=>({width:innerWidth,actual:document.documentElement.scrollWidth}));assert.ok(d.actual<=d.width+1,JSON.stringify(d))}
try{
 await api('/auth/login','POST',{email:'admin@example.test',password:'Integration-Test-Password-2026!'});
 await page.goto(base+'/app/system-status');await page.getByLabel('워크스페이스 선택',{exact:true}).selectOption(wid);
 await page.goto(base+`/app/system-status?document=${doc}`);await expect(page.getByText('관리자가 운영 보고를 활성화하지 않았습니다. 기존 이력은 과거 자료이며 현재 상태로 확인하지 않습니다.',{exact:true})).toBeVisible();
 await page.getByRole('link',{name:'보고 정책',exact:true}).click();await expect(page.getByRole('heading',{name:'시스템 운영 보고 정책',exact:true})).toBeVisible();
 await page.getByRole('checkbox',{name:'운영 카드 등록과 관측 보고 수신을 허용합니다',exact:true}).check();await expect(page.getByRole('button',{name:'보고 정책 저장',exact:true})).toBeDisabled();await page.getByRole('checkbox',{name:'보고 수신·만료·보존 범위와 삭제 영향을 확인했습니다.',exact:true}).check();await page.getByRole('button',{name:'보고 정책 저장',exact:true}).click();await expect(page.getByText('보고 정책을 저장했습니다. 기존 기대값·관측이 실제 배포 확인으로 바뀌지는 않습니다.',{exact:true})).toBeVisible();await shot('system-status-policy');
 await page.goto(base+`/app/system-status?document=${doc}`);await page.getByRole('button',{name:'운영 카드 등록',exact:true}).click();
 const modal=page.getByRole('dialog');await modal.getByLabel('시스템 이름',{exact:true}).fill('madi 운영 검증');await modal.getByLabel('운영 환경',{exact:true}).fill('폐쇄망 테스트');await modal.getByLabel('기대 시스템 버전',{exact:true}).fill('v1.0.0');await modal.getByLabel('기대 배포 식별자',{exact:true}).fill('release-blue');await modal.getByLabel('보고 주체 · 여러 계정은 Ctrl/⌘로 선택',{exact:true}).selectOption(uid);await expect(modal.getByRole('button',{name:'운영 기준 저장',exact:true})).toBeDisabled();await modal.getByRole('checkbox').check();await modal.getByRole('button',{name:'운영 기준 저장',exact:true}).click();await expect(page.locator('[data-status-state]')).toHaveAttribute('data-status-state','unobserved');await shot('system-status-unobserved');
 const original=await api('/documents/'+doc);assert.equal(original.version,1);
 await page.getByRole('button',{name:'실제 관측 보고',exact:true}).click();await modal.getByLabel('관측한 시스템 버전',{exact:true}).fill('v0.9.0');await modal.getByLabel('관측한 배포 식별자',{exact:true}).fill('release-green');await modal.getByLabel('관측한 상태',{exact:true}).selectOption('degraded');await modal.getByLabel('관측 근거 메모',{exact:true}).fill('보고 주체가 직접 확인한 합성 관측입니다. 독립 검증은 아닙니다.');await expect(modal.getByRole('checkbox')).not.toBeChecked();await modal.getByRole('checkbox').check();await modal.getByRole('button',{name:'관측 보고 저장',exact:true}).click();await expect(page.locator('[data-status-state]')).toHaveAttribute('data-status-state','drift');await overflow();await shot('system-status-drift');
 let state=await api('/documents/'+doc+'/system-status');assert.equal(state.latest_report.actor_kind,'manual');assert.equal(state.summary.independently_verified,false);assert.equal(state.reports.length,1);assert.equal((await api('/documents/'+doc)).markdown,original.markdown);
 // A second tab changes the CAS baseline while this dialog is open.
 await page.getByRole('button',{name:'실제 관측 보고',exact:true}).click();await modal.getByLabel('관측한 시스템 버전',{exact:true}).fill('v1.0.0');await modal.getByRole('checkbox').check();
 await api('/documents/'+doc+'/system-status','PUT',{revision:state.card.revision,document_version:1,owner_id:uid,reporter_ids:[uid],ttl_seconds:300,expected:{...state.card.expected,version:'v1.1.0'},confirm:true});
 await expect(modal.getByRole('checkbox')).not.toBeChecked({timeout:7000});await expect(modal.getByRole('button',{name:'관측 보고 저장',exact:true})).toBeDisabled();await modal.getByRole('button',{name:'취소',exact:true}).click();await expect(page.locator('[data-status-state]')).toHaveAttribute('data-status-state','baseline_changed');
 await page.setViewportSize({width:390,height:844});await page.waitForFunction(()=>matchMedia('(max-width:640px)').matches&&getComputedStyle(document.querySelector('.main')).marginLeft==='0px',null,{timeout:2000});await page.evaluate(()=>scrollTo(0,0));await overflow();await shot('system-status-mobile');
 await page.locator('.status-comparison article').nth(1).scrollIntoViewIfNeeded();await overflow();await shot('system-status-observation-mobile');
 // Current document and card revision remain separate; only explicit report changes report history.
 state=await api('/documents/'+doc+'/system-status');assert.equal(state.reports.length,1);await api('/documents/'+doc,'PUT',{version:1,markdown:original.markdown+'\n변경된 검토 기준'});await expect(page.locator('[data-status-state]')).toHaveAttribute('data-status-state','document_changed',{timeout:7000});await expect(page.getByRole('button',{name:'실제 관측 보고',exact:true})).toBeDisabled();
 // Read-only collaborator sees no administrator bypass after private change.
 const viewer=await api('/admin/users','POST',{email:'status-browser-viewer@example.test',name:'관측 열람자',role:'viewer',password:'Status-Viewer-Password-2026!'});await api('/workspaces/'+wid+'/members','PUT',{email:viewer.email,role:'viewer'});
 const second=await browser.newContext({viewport:{width:1200,height:900},locale:'ko-KR'});try{const login=await second.request.post(base+'/api/v1/auth/login',{data:{email:viewer.email,password:'Status-Viewer-Password-2026!'},headers:{'X-Madi-Request':'1'}});assert.equal(login.status(),200);const vp=await second.newPage();await vp.goto(base+`/app/system-status?document=${doc}`);await expect(vp.locator('.status-comparison')).toContainText('release-green');await api('/documents/'+doc,'PUT',{version:2,visibility:'private'});await expect(vp.locator('.status-comparison')).toHaveCount(0,{timeout:7000})}finally{await second.close()}
 assert.deepEqual(issues,[]);console.log(JSON.stringify({ok:true,checks:['default-off-policy','explicit-readers-reporters','expected-not-observed','real-report-drift','canonical-unchanged','CAS-reconfirmation','doc-version-changed','current-ACL-revocation','mobile390'],screenshots:output}));
}catch(e){await shot('failure').catch(()=>{});console.error(await page.locator('body').innerText());throw e}finally{await browser.close()}
