\set ON_ERROR_STOP on
-- Diagnostic only: all tables and indexes are session-local TEMP objects.
-- Run against a selected, disposable test database. Closing psql removes them.
-- No production tables, schemas, settings, or statistics are modified.
-- Do not treat shared-host timings as a performance guarantee.

SET statement_timeout='25s';
CREATE TEMP TABLE documents(n int PRIMARY KEY,id uuid NOT NULL);
INSERT INTO documents SELECT n,md5(n::text)::uuid FROM generate_series(1,10000)n;
CREATE TEMP TABLE audit_logs(id uuid PRIMARY KEY,user_id uuid,action text NOT NULL,resource text NOT NULL,details jsonb NOT NULL DEFAULT '{}',created_at timestamptz NOT NULL);
CREATE INDEX audit_created_idx ON audit_logs(created_at DESC);
CREATE INDEX audit_resource_created_idx ON audit_logs(resource,created_at DESC);
CREATE INDEX audit_action_created_idx ON audit_logs(action,created_at DESC);
CREATE INDEX audit_document_popularity_idx ON audit_logs(resource,created_at DESC) INCLUDE(user_id) WHERE action='DOCUMENT_READ';
INSERT INTO audit_logs SELECT md5(('other'||n)::text)::uuid,md5('1')::uuid,'SEARCH','workspace',jsonb_build_object('padding',repeat('x',150)),now()-n*interval '1 second' FROM generate_series(1,300)n;
ANALYZE documents; ANALYZE audit_logs;
INSERT INTO audit_logs SELECT md5(('read'||n)::text)::uuid,md5((n%31)::text)::uuid,'DOCUMENT_READ',md5('1')::uuid::text,jsonb_build_object('padding',repeat('x',150)),now()-n*interval '1 second' FROM generate_series(1,130)n;
CREATE TEMP TABLE diag_plans(stage text,variant text,plan jsonb);
DO $$DECLARE plan jsonb;BEGIN EXECUTE 'EXPLAIN (ANALYZE,BUFFERS,FORMAT JSON) SELECT d.id,(SELECT 0.25*least(1.0,count(DISTINCT seen.user_id)/20.0) FROM (SELECT a.user_id FROM audit_logs a WHERE a.action=''DOCUMENT_READ'' AND a.resource=d.id::text AND a.created_at>now()-interval ''30 days'' ORDER BY a.created_at DESC LIMIT 256) seen) score FROM documents d WHERE d.n%5<>0' INTO plan;INSERT INTO diag_plans VALUES('stale_statistics','baseline',plan);END$$;
DO $$DECLARE plan jsonb;BEGIN EXECUTE 'EXPLAIN (ANALYZE,BUFFERS,FORMAT JSON) SELECT d.id,(SELECT 0.25*least(1.0,count(DISTINCT seen.user_id)/20.0) FROM (SELECT a.user_id FROM audit_logs a WHERE a.action=''DOCUMENT_READ'' AND a.resource=d.id::text AND a.created_at>now()-interval ''30 days'' ORDER BY a.resource,a.created_at DESC LIMIT 256) seen) score FROM documents d WHERE d.n%5<>0' INTO plan;INSERT INTO diag_plans VALUES('stale_statistics','resource_first_order',plan);END$$;
DO $$DECLARE plan jsonb;BEGIN EXECUTE 'EXPLAIN (ANALYZE,BUFFERS,FORMAT JSON) SELECT d.id,(SELECT 0.25*least(1.0,count(DISTINCT seen.user_id)/20.0) FROM (SELECT a.user_id FROM (SELECT user_id,created_at FROM audit_logs WHERE action=''DOCUMENT_READ'' AND resource=d.id::text OFFSET 0) a WHERE a.created_at>now()-interval ''30 days'' ORDER BY a.created_at DESC LIMIT 256) seen) score FROM documents d WHERE d.n%5<>0' INTO plan;INSERT INTO diag_plans VALUES('stale_statistics','resource_barrier',plan);END$$;
DO $$DECLARE plan jsonb;BEGIN EXECUTE 'EXPLAIN (ANALYZE,BUFFERS,FORMAT JSON) SELECT d.id,(SELECT 0.25*least(1.0,count(DISTINCT seen.user_id)/20.0) FROM (SELECT a.user_id FROM audit_logs a WHERE a.action=''DOCUMENT_READ'' AND a.resource=ANY(ARRAY[d.id::text]) AND a.created_at>now()-interval ''30 days'' ORDER BY a.created_at DESC LIMIT 256) seen) score FROM documents d WHERE d.n%5<>0' INTO plan;INSERT INTO diag_plans VALUES('stale_statistics','singleton_any',plan);END$$;
ANALYZE audit_logs;
DO $$DECLARE plan jsonb;BEGIN EXECUTE 'EXPLAIN (ANALYZE,BUFFERS,FORMAT JSON) SELECT d.id,(SELECT 0.25*least(1.0,count(DISTINCT seen.user_id)/20.0) FROM (SELECT a.user_id FROM audit_logs a WHERE a.action=''DOCUMENT_READ'' AND a.resource=d.id::text AND a.created_at>now()-interval ''30 days'' ORDER BY a.created_at DESC LIMIT 256) seen) score FROM documents d WHERE d.n%5<>0' INTO plan;INSERT INTO diag_plans VALUES('fresh_statistics','baseline',plan);END$$;
DO $$DECLARE plan jsonb;BEGIN EXECUTE 'EXPLAIN (ANALYZE,BUFFERS,FORMAT JSON) SELECT d.id,(SELECT 0.25*least(1.0,count(DISTINCT seen.user_id)/20.0) FROM (SELECT a.user_id FROM audit_logs a WHERE a.action=''DOCUMENT_READ'' AND a.resource=d.id::text AND a.created_at>now()-interval ''30 days'' ORDER BY a.resource,a.created_at DESC LIMIT 256) seen) score FROM documents d WHERE d.n%5<>0' INTO plan;INSERT INTO diag_plans VALUES('fresh_statistics','resource_first_order',plan);END$$;
DO $$DECLARE plan jsonb;BEGIN EXECUTE 'EXPLAIN (ANALYZE,BUFFERS,FORMAT JSON) SELECT d.id,(SELECT 0.25*least(1.0,count(DISTINCT seen.user_id)/20.0) FROM (SELECT a.user_id FROM (SELECT user_id,created_at FROM audit_logs WHERE action=''DOCUMENT_READ'' AND resource=d.id::text OFFSET 0) a WHERE a.created_at>now()-interval ''30 days'' ORDER BY a.created_at DESC LIMIT 256) seen) score FROM documents d WHERE d.n%5<>0' INTO plan;INSERT INTO diag_plans VALUES('fresh_statistics','resource_barrier',plan);END$$;
DO $$DECLARE plan jsonb;BEGIN EXECUTE 'EXPLAIN (ANALYZE,BUFFERS,FORMAT JSON) SELECT d.id,(SELECT 0.25*least(1.0,count(DISTINCT seen.user_id)/20.0) FROM (SELECT a.user_id FROM audit_logs a WHERE a.action=''DOCUMENT_READ'' AND a.resource=ANY(ARRAY[d.id::text]) AND a.created_at>now()-interval ''30 days'' ORDER BY a.created_at DESC LIMIT 256) seen) score FROM documents d WHERE d.n%5<>0' INTO plan;INSERT INTO diag_plans VALUES('fresh_statistics','singleton_any',plan);END$$;
CREATE INDEX audit_action_resource_cover_idx ON audit_logs(action,resource,created_at DESC) INCLUDE(user_id);
DO $$DECLARE plan jsonb;BEGIN EXECUTE 'EXPLAIN (ANALYZE,BUFFERS,FORMAT JSON) SELECT d.id,(SELECT 0.25*least(1.0,count(DISTINCT seen.user_id)/20.0) FROM (SELECT a.user_id FROM audit_logs a WHERE a.action=''DOCUMENT_READ'' AND a.resource=d.id::text AND a.created_at>now()-interval ''30 days'' ORDER BY a.created_at DESC LIMIT 256) seen) score FROM documents d WHERE d.n%5<>0' INTO plan;INSERT INTO diag_plans VALUES('full_covering_index','baseline',plan);END$$;
DO $$DECLARE plan jsonb;BEGIN EXECUTE 'EXPLAIN (ANALYZE,BUFFERS,FORMAT JSON) SELECT d.id,(SELECT 0.25*least(1.0,count(DISTINCT seen.user_id)/20.0) FROM (SELECT a.user_id FROM audit_logs a WHERE a.action=''DOCUMENT_READ'' AND a.resource=d.id::text AND a.created_at>now()-interval ''30 days'' ORDER BY a.resource,a.created_at DESC LIMIT 256) seen) score FROM documents d WHERE d.n%5<>0' INTO plan;INSERT INTO diag_plans VALUES('full_covering_index','resource_first_order',plan);END$$;
DO $$DECLARE plan jsonb;BEGIN EXECUTE 'EXPLAIN (ANALYZE,BUFFERS,FORMAT JSON) SELECT d.id,(SELECT 0.25*least(1.0,count(DISTINCT seen.user_id)/20.0) FROM (SELECT a.user_id FROM (SELECT user_id,created_at FROM audit_logs WHERE action=''DOCUMENT_READ'' AND resource=d.id::text OFFSET 0) a WHERE a.created_at>now()-interval ''30 days'' ORDER BY a.created_at DESC LIMIT 256) seen) score FROM documents d WHERE d.n%5<>0' INTO plan;INSERT INTO diag_plans VALUES('full_covering_index','resource_barrier',plan);END$$;
DO $$DECLARE plan jsonb;BEGIN EXECUTE 'EXPLAIN (ANALYZE,BUFFERS,FORMAT JSON) SELECT d.id,(SELECT 0.25*least(1.0,count(DISTINCT seen.user_id)/20.0) FROM (SELECT a.user_id FROM audit_logs a WHERE a.action=''DOCUMENT_READ'' AND a.resource=ANY(ARRAY[d.id::text]) AND a.created_at>now()-interval ''30 days'' ORDER BY a.created_at DESC LIMIT 256) seen) score FROM documents d WHERE d.n%5<>0' INTO plan;INSERT INTO diag_plans VALUES('full_covering_index','singleton_any',plan);END$$;
SELECT jsonb_build_object('stage',stage,'variant',variant,'execution_ms',plan->0->>'Execution Time','index_scans',(SELECT jsonb_agg(DISTINCT jsonb_build_object('index',x->>'Index Name','loops',x->>'Actual Loops','rows',x->>'Actual Rows','filtered',x->>'Rows Removed by Filter','condition',x->>'Index Cond','local_hits',x->>'Local Hit Blocks')) FROM jsonb_path_query(plan,'$[0].Plan.** ? (@."Index Name" != null)')x)) FROM diag_plans;
