import {useCallback,useEffect,useRef,useState} from 'react';
import {Link,useSearchParams} from 'react-router-dom';
import {Download,FileArchive,RefreshCw,ShieldCheck,Trash2} from 'lucide-react';
import {api,bytes,datetime,download} from './api';
import {useApp} from './context';
import {Badge,Button,Empty,ErrorBox,Field,Loading,PageHeading} from './ui';
import './transfer.css';
type Row=Record<string,any>;
const formats=[['markdown','Markdown 원문 ZIP'],['portable','Markdown 이동용 ZIP'],['html','HTML 읽기 전용 ZIP'],['json','JSON 지식 보관함'],['csv','데이터베이스 CSV']];
const labels:Record<string,string>={queued:'대기',running:'생성 중',ready:'다운로드 준비',failed:'실패',cancelled:'취소',expired:'만료'};
export function ExportPage(){
 const {workspace,documents,notify}=useApp();const [params,setParams]=useSearchParams();
 const [rows,setRows]=useState<Row[]>([]),[databases,setDatabases]=useState<Row[]>([]),[format,setFormat]=useState('markdown'),[selected,setSelected]=useState<string[]>([]),[database,setDatabase]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[query,setQuery]=useState('');
 const scope=workspace?.id||'',latest=useRef(scope),generation=useRef(0),operation=useRef(0);latest.current=scope;
 const load=useCallback(async()=>{const current=scope,run=++generation.current;if(!scope){setLoading(false);return};try{const [a,b]=await Promise.all([api<Row[]>(`/exports?workspace_id=${scope}`),api<Row[]>(`/databases?workspace_id=${scope}`)]);if(latest.current===current&&run===generation.current){setRows(a);setDatabases(b)}}catch(e){if(latest.current===current&&run===generation.current)setError((e as Error).message)}finally{if(latest.current===current&&run===generation.current)setLoading(false)}},[scope]);
 useEffect(()=>{operation.current++;setRows([]);setDatabases([]);setSelected([]);setDatabase('');setBusy(false);setError('');setLoading(true);void load();return()=>{generation.current++;operation.current++}},[load]);
 useEffect(()=>{if(!rows.some(x=>['queued','running'].includes(x.status)))return;const timer=setInterval(()=>void load(),2000);return()=>clearInterval(timer)},[rows,load]);
 const execute=async(fn:(alive:()=>boolean)=>Promise<void>)=>{const start=scope,op=++operation.current;const alive=()=>latest.current===start&&op===operation.current;setBusy(true);setError('');try{await fn(alive)}catch(e){if(alive())setError((e as Error).message)}finally{if(alive())setBusy(false)}};
 const visible=documents.filter(x=>x.workspace_id===scope&&!x.deleted_at&&x.title.toLowerCase().includes(query.toLowerCase()));
 return <><PageHeading eyebrow="PORTABLE KNOWLEDGE" title="내보내기 센터" description="원문과 첨부를 확인하고, 현재 권한으로 다시 읽을 수 있는 파일을 만듭니다." actions={<><Link className="button" to="/app/import">가져오기 센터</Link><Button onClick={()=>void load()}><RefreshCw size={17}/>새로고침</Button></>}/><ErrorBox error={error}/><div className="notice subtle"><ShieldCheck size={22}/><span>결과는 암호화하여 24시간만 보관합니다. 원본·첨부·권한이 바뀌거나 요청한 로그인 세션이 끝나면 다시 생성해야 합니다. 임시 결과는 백업에 포함되지 않습니다.</span></div>
 <form className="transfer-card" onSubmit={e=>{e.preventDefault();void execute(async alive=>{const created=await api<Row>('/exports','POST',{workspace_id:scope,format,document_ids:format==='csv'?[]:selected,database_id:format==='csv'?database:''});if(!alive())return;setParams({export:created.id});notify('내보내기 작업을 등록했습니다');await load()})}}>
 <div className="form-grid"><Field label="내보내기 형식"><select value={format} onChange={e=>setFormat(e.target.value)}>{formats.map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></Field><div className="notice subtle">{format==='markdown'?'본문·Front Matter 바이트를 그대로 보존합니다. 원래 링크는 바꾸지 않으며 manifest로 첨부/문서 ID를 기록합니다.':format==='portable'?'다른 Markdown 도구에서 읽기 쉽도록 문서·첨부 링크를 상대 경로로 바꿉니다. 원문 바이트와 다를 수 있습니다.':format==='html'?'인터넷 없이 읽는 HTML과 로컬 첨부를 ZIP으로 만듭니다. 원본 편집·실시간 권한은 포함하지 않습니다.':format==='json'?'madi-json-vault 버전 1: 원문·폴더·첨부와 manifest를 보관합니다. 다시 가져올 때 새 비공개 초안으로 생성합니다.':'저장된 속성 값을 UTF-8 CSV로 만듭니다. 최대 10,000행이며 수식 실행 위험이 있는 셀에는 작은따옴표를 붙입니다.'}</div></div>
 {format==='csv'?<Field label="내보낼 데이터베이스"><select value={database} onChange={e=>setDatabase(e.target.value)} required><option value="">데이터베이스 선택</option>{databases.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field>:<><div className="section-heading"><h2>선택 문서 <Badge>{selected.length}개</Badge></h2><Button type="button" onClick={()=>setSelected(visible.slice(0,1000).map(x=>x.id))}>표시 문서 선택</Button><Button type="button" onClick={()=>setSelected([])}>선택 해제</Button></div><Field label="문서 이름 검색"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="내보낼 문서를 찾아보세요"/></Field><div className="transfer-docs">{visible.map(d=><label key={d.id}><input type="checkbox" checked={selected.includes(d.id)} onChange={e=>setSelected(old=>e.target.checked?[...old,d.id]:old.filter(id=>id!==d.id))}/><span>{d.title}<small>{d.visibility==='private'?'개인 문서':'공유 문서'} · 버전 {d.version}</small></span></label>)}{!visible.length&&<p className="muted">선택할 문서가 없습니다.</p>}</div><p className="muted">한 번에 문서 최대 1,000개 · 파일 최대 5,000개 · 관리자 크기 정책 최대 100MB</p></>}
 <Button variant="primary" disabled={busy||(format==='csv'?!database:!selected.length)}><FileArchive size={18}/>{busy?'작업 등록 중…':'선택한 자료 내보내기'}</Button></form>
 <section className="transfer-history"><div className="section-heading"><h2>내 결과 파일</h2><Link to="/app/jobs">작업 이력</Link></div>{loading?<Loading/>:rows.length?<div className="transfer-results">{rows.map(row=><article className={`transfer-card ${params.get('export')===row.id?'selected':''}`} key={row.id}><div className="section-heading"><h3>{formats.find(x=>x[0]===row.format)?.[1]}</h3><Badge tone={row.status==='ready'?'green':''}>{labels[row.status]||row.status}</Badge></div><p className="muted">요청 {datetime(row.created_at)}<br/>만료 {datetime(row.expires_at)} · {bytes(row.artifact_bytes)}</p>{row.report?.error&&<ErrorBox error={row.report.error}/>}<div className="button-row">{row.status==='ready'&&<Button disabled={busy} variant="primary" onClick={()=>void execute(async alive=>{await download(`/exports/${row.id}/download`,row.filename);if(alive())notify('내보내기 파일을 다운로드했습니다')})}><Download size={17}/>파일 다운로드</Button>}{['queued','running','ready'].includes(row.status)&&<Button disabled={busy} onClick={()=>void execute(async alive=>{await api(`/exports/${row.id}`,'DELETE');if(!alive())return;notify('내보내기 작업과 임시 파일을 폐기했습니다');await load()})}><Trash2 size={16}/>취소 · 임시 파일 폐기</Button>}</div></article>)}</div>:<Empty title="내보낸 파일이 없습니다" text="문서를 선택하면 백그라운드에서 결과 파일을 만듭니다."/>}</section><p className="notice subtle">PDF는 문서 화면의 인쇄 기능에서 브라우저의 ‘PDF로 저장’을 선택하세요. 서버 PDF 변환 작업이 아닙니다. 이미 내려받은 사본에는 이후 권한 변경이나 삭제가 반영되지 않습니다.</p></>;
}
export function ExportPolicyPage(){
 const [value,setValue]=useState<Row|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);const {notify}=useApp();
 useEffect(()=>{let active=true;api<Row>('/admin/exports/settings').then(x=>{if(active)setValue(x)}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[]);
 const save=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);try{await api('/admin/exports/settings','PUT',value);setValue(await api('/admin/exports/settings'));notify('내보내기 정책을 저장했습니다')}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 return <><PageHeading eyebrow="DATA PORTABILITY" title="내보내기 정책" description="비동기 내보내기의 사용 여부와 임시 결과 크기를 관리합니다."/><ErrorBox error={error}/>{value?<form className="transfer-card" onSubmit={save}><Field label="내보내기 사용"><select value={String(value.enabled)} onChange={e=>setValue({...value,enabled:e.target.value==='true'})}><option value="true">사용</option><option value="false">사용 중지</option></select></Field><Field label="결과 파일 최대 크기 (MB)" hint="1~100MB · 개인별 보관 합계 200MB · 대기 작업 5개 · 보관 24시간"><input type="number" min={1} max={100} value={value.max_archive_mb} onChange={e=>setValue({...value,max_archive_mb:Number(e.target.value)})}/></Field><p className="notice subtle">설정을 변경하면 이전 결과는 재생성이 필요합니다. 복원 후에는 내보내기를 다시 활성화하세요. 임시 결과 파일은 백업 대상이 아닙니다.</p><Button variant="primary" disabled={busy}>정책 저장</Button></form>:<Loading/>}</>;
}
